######################################################################
# Automatically generated by qmake (3.0) Thu Apr 6 08:32:12 2017
######################################################################

TEMPLATE = app
TARGET = diffML++
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += inc/diffML.hpp
SOURCES += src/diffML.cpp
