######################################################################
# Automatically generated by qmake (3.0) Thu Apr 6 08:46:39 2017
######################################################################

TEMPLATE = app
TARGET = diffML++
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += inc/diffML.hpp inc/main.hpp inc/treemodel.hpp
SOURCES += src/diffML.cpp src/main.cpp src/treemodel.cpp

