######################################################################
# Automatically generated by qmake (3.0) Tue Apr 11 06:31:44 2017
######################################################################

TEMPLATE = app
TARGET = diffML++
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += inc/diffML.hpp inc/main.hpp inc/treeitem.hpp inc/treemodel.hpp
SOURCES += src/diffML.cpp src/main.cpp src/treeitem.cpp src/treemodel.cpp
