#!/usr/bin/python3

from pyautogui import press, moveTo, click, hotkey
from subprocess import Popen, PIPE
from threading import Thread
from sys import argv
from time import sleep
from csv import reader

def kill(ip):
    print(ip)
    P = Popen('echo "hhadmin" | vncviewer -autopass '+ ip, shell=True)

    sleep(1)

    info = Popen('xdotool search --name "'+ ip + '" getwindowgeometry', stdout = PIPE, shell=True)

    info = str(info.communicate()[0])

    if info != "b''":
        info = info.split(":")[1]
        info = info.split(" ")[1]
        f, s = info.split(",")
        f = int(f) + 50
        s = int(s) + 50

        moveTo(f,s)
        click()
        sleep(.5)
        click()
        moveTo(f+50,s+50,1)
        click()
        sleep(.5)
        click()

        sleep(2)

        hotkey("alt", "f4")
        sleep(2)
        hotkey("alt", "f4")
        sleep(2)
        hotkey("alt", "f4")
        sleep(2)
        hotkey("alt", "f4")
        sleep(1)
        press("enter")

    Popen('xdotool search --name "'+ ip + '" windowkill', stdout = PIPE, shell=True)

    sleep(1)

if len(argv) == 2:
    if len(argv[1]) == 3:
        ip = "10.12.224." + argv[1]
        kill(ip)
    else:
        kill(argv[1])
else:
    print("Are you sure you want to kill all? (y/N)")
    r = input()
    if r != "N":
        with open("hmis.csv", "r") as csvFile:
            r = reader(csvFile)
            for i in r: 
                #Thread(target = kill, args = (i)).start()
                kill(i[0])
