#!/usr/bin/python3

from PyQt5.QtCore import QFile, QIODevice
from PyQt5.QtWidgets import QApplication, QTreeView, QGridLayout, QWidget, QFileDialog, QPushButton, QMainWindow, QAction
import sys

from lib.treelib import TreeModel
import simpletreemodel_rc



class Application(QMainWindow):
    def __init__(self):
        super().__init__()

        frame = QWidget()
        self.setCentralWidget(frame)
        grid = QGridLayout()
        frame.setLayout(grid)

        self.initMenuBar()

        leftXMLView = QTreeView()
        leftXMLView.setModel(model)
        grid.addWidget(leftXMLView,0,0)

        rightXMLView = QTreeView()
        rightXMLView.setModel(model)
        grid.addWidget(rightXMLView,0,1)

        self.show()
    
    def initMenuBar(self):
        menubar = self.menuBar()

        fileMenu = menubar.addMenu('&File')

        openLeftXML = QAction('&Open Left XML',self)
        openLeftXML.triggered.connect(self.findFile)
        fileMenu.addAction(openLeftXML)

        openRightXML = QAction('&Open Right XML',self)
        openRightXML.triggered.connect(self.findFile)
        fileMenu.addAction(openRightXML)

        editMenu = menubar.addMenu('&Edit')

        helpMenu = menubar.addMenu('&Help')

    def findFile(self):
        options = QFileDialog.Options()
        QFileDialog.getOpenFileName(self)

app = QApplication(sys.argv)

f = QFile(':/default.txt')
f.open(QIODevice.ReadOnly)
model = TreeModel(f.readAll())
f.close()

masterView = Application()

sys.exit(app.exec_())
