#!/usr/bin/python3

from PyQt5.QtCore import QFile, QIODevice
from PyQt5.QtWidgets import QApplication, QTreeView, QGridLayout, QWidget, QFileDialog, QPushButton, QMainWindow, QAction
import sys

from lib.treelib import TreeModel
from lib.xmllib import getXML

class xmlDiff(QMainWindow):
    def __init__(self):
        super().__init__()

        frame = QWidget()
        self.setCentralWidget(frame)
        grid = QGridLayout()
        frame.setLayout(grid)

        self.initMenuBar()

        self.leftXMLView = QTreeView()
        grid.addWidget(self.leftXMLView,0,0)

        self.rightXMLView = QTreeView()
        grid.addWidget(self.rightXMLView,0,1)

        self.show()
    
    def initMenuBar(self):
        menubar = self.menuBar()

        fileMenu = menubar.addMenu('&File')

        openLeftXML = QAction('&Open Left XML',self)
        openLeftXML.triggered.connect(lambda : self.findFile("left"))
        fileMenu.addAction(openLeftXML)

        openRightXML = QAction('&Open Right XML',self)
        openRightXML.triggered.connect(lambda : self.findFile("right"))
        fileMenu.addAction(openRightXML)

        editMenu = menubar.addMenu('&Edit')

        helpMenu = menubar.addMenu('&Help')

    def findFile(self,which):
        path = QFileDialog.getOpenFileName(self)
        if path:
            xmlData = getXML(path[0]) 
            model = TreeModel(xmlData)
            if which == "left":
                self.leftXMLView.setModel(model)
            else:
                self.rightXMLView.setModel(model)


app = QApplication(sys.argv)

masterView = xmlDiff()

sys.exit(app.exec_())
