#!/usr/bin/python3

from tkinter import Tk, Frame, Button, Listbox, OptionMenu, StringVar, Toplevel, Message, Listbox, END, Entry, ACTIVE, messagebox
from os import listdir

from lib.datalib import diffRecipes
from lib.xmllib import getXML
from lib.csvlib import writeCSVVarsDiff

class recipeDiff(Frame):
    def __init__(self, master):
        self.master = master

        self.filled1 = False
        self.filled2 = False
        
        # ROW 0
        options = []
        for f in listdir("xmldata"):
            options.append(f)

        self.file1Selection = StringVar()
        self.file1Selection.set(options[0])

        self.file2Selection = StringVar()
        self.file2Selection.set(options[0])

        file1 = OptionMenu(master, self.file1Selection, *options)
        file1.grid(column = 0, row = 0)

        file2 = OptionMenu(master, self.file2Selection, *options)
        file2.grid(column = 1, row = 0)

        # ROW 1
        Button(master, text="Get Recipes", command = self.getData).grid(row=1, columnspan=2)
        
        # ROW 2
        self.file1Screens = Listbox(master)
        self.file1Screens.grid(column=0,row=2)
        self.file1Screens.bind('<Double-1>', lambda a: self.sendToCompare(1) )

        self.file2Screens = Listbox(master)
        self.file2Screens.grid(column=1,row=2)
        self.file2Screens.bind('<Double-1>', lambda a: self.sendToCompare(2) )

        # ROW 5
        self.data1Select = Entry(master)
        self.data1Select.grid(row = 5, column = 0)

        self.data2Select = Entry(master)
        self.data2Select.grid(row = 5, column = 1)

        # ROW 6   
        self.compareButton = Button(master, text="Compare", command = self.compare)
        self.compareButton.grid(row = 6, columnspan = 2)
        self.compareButton.config(state="disabled")

    def getData(self):
        self.data1 = getXML(self.file1Selection.get())
        self.data2 = getXML(self.file2Selection.get())

        for group in self.data1:
            for recipe in group['recipes']:
                self.file1Screens.insert(END,recipe['name'])

        for group in self.data2:
            for recipe in group['recipes']:
                self.file2Screens.insert(END,recipe['name'])

    def sendToCompare(self, f):
        if f == 1:
            self.data1Select.delete(0,END)
            self.data1Select.insert(0,self.file1Screens.get(ACTIVE))
            self.filled1 = True
        elif f == 2:
            self.data2Select.delete(0,END)
            self.data2Select.insert(0,self.file2Screens.get(ACTIVE))
            self.filled2 = True
        if self.filled1 and self.filled2:
            self.compareButton.config(state="normal")

    def compare(self):
        for group in self.data1:
            for recipe in group["recipes"]:
                if recipe["name"] == self.data1Select.get():
                    recipe1 = recipe
        
        for group in self.data2:
            for recipe in group["recipes"]:
                if recipe["name"] == self.data2Select.get():
                    recipe2 = recipe

        diffData = diffRecipes(recipe1["vars"],recipe2["vars"])

        lastRow = len(diffData["data1missing"])
        if lastRow <= len(diffData["data2missing"]):
            lastRow = len(diffData["data2missing"])
        lastRow = lastRow + 1

        if lastRow == 1:
            messagebox.showinfo("Result","They have no variable differences.")
        else:
            top = Toplevel()
            top.columnconfigure(0,minsize=200)
            top.columnconfigure(1,minsize=200)

            titleLeft = Message(top, text=(self.file1Selection.get() + " is missing:"))
            titleLeft.config(aspect=400)
            titleLeft.grid(row=0,column=0)
            titleRight = Message(top, text=(self.file2Selection.get() + " is missing:"))
            titleRight.config(aspect=400)
            titleRight.grid(row=0,column=1)

            for index, screen in enumerate(diffData["data1missing"]):
                tmp = Message(top,text=screen)
                tmp.config(aspect=2000)
                tmp.grid(row=index+1,column=0)
            
            for index, screen in enumerate(diffData["data2missing"]):
                tmp = Message(top,text=screen)
                tmp.config(aspec=2000)
                tmp.grid(row=index+1,column=1)

            Button(top, text="Okay", command=top.destroy).grid(column=0, row=lastRow)
            Button(top, text="Save to CSV", command=lambda : writeCSVVarsDiff(diffData)).grid(column=1, row=lastRow)



        

root = Tk()
root.title("recipeDiff")
app = recipeDiff(master = root)
root.mainloop()
