######################################################################		
# Automatically generated by qmake (3.0) Tue Apr 11 06:31:44 2017		
######################################################################		
	
TEMPLATE = app		
TARGET = diffML++		
INCLUDEPATH += .		
QT += widgets		
LIBS += -lxml2		
OBJECTS_DIR = tmp		
MOC_DIR = tmp		

# Input		
HEADERS += inc/*		
SOURCES += src/*
