#!/usr/bin/python3

from tkinter import Tk, Frame, Button, Listbox, OptionMenu, StringVar, Toplevel, Message, Listbox, END, Entry, ACTIVE, messagebox, ALL, DoubleVar
from os import listdir

from lib.xmllib import getXML
from lib.csvlib import writeCSV, readCSV, writeCSVDiff, writeCSVScreensDiff
from lib.datalib import diffScreens, diffAll, diffScreenVars

class XMLDiffer(Frame):
    def __init__(self, master):
        self.master = master

        self.filled1 = False
        self.filled2 = False

        textWidth = 45
        
        # ROW 0
        options = []
        for f in listdir("xmldata"):
            options.append(f)

        self.file1Selection = StringVar()
        self.file1Selection.set(options[0])

        self.file2Selection = StringVar()
        self.file2Selection.set(options[0])

        file1 = OptionMenu(master, self.file1Selection, *options)
        file1.grid(column = 0, row = 0)

        file2 = OptionMenu(master, self.file2Selection, *options)
        file2.grid(column = 1, row = 0)

        # ROW 1
        Button(master, text="Get Screens", command=self.getData).grid(column = 1, row=1)

        versions = [6.5, 7.2]
        self.versionSelection = DoubleVar()
        self.versionSelection.set(versions[0])

        version = OptionMenu(master, self.versionSelection, *versions)
        version.grid(column = 0, row = 1)

        # ROW 2
        self.file1Screens = Listbox(master,width=textWidth)
        self.file1Screens.grid(column=0,row=2)
        self.file1Screens.bind('<Double-1>', lambda a: self.sendToCompare(1) )

        self.file2Screens = Listbox(master,width=textWidth)
        self.file2Screens.grid(column=1,row=2)
        self.file2Screens.bind('<Double-1>', lambda a: self.sendToCompare(2) )

        # ROW 3
        self.file1CsvButton = Button(master, text="Save to CSV", command = lambda: self.saveCSV(1))
        self.file1CsvButton.grid(row=3, column=0)
        self.file1CsvButton.config(state="disabled")

        self.file2CsvButton = Button(master, text="Save to CSV", command = lambda: self.saveCSV(2))
        self.file2CsvButton.grid(row=3, column=1)
        self.file2CsvButton.config(state="disabled")

        # ROW 4
        self.diffButton = Button(master, text="Compare Screens", command = self.checkMissingScreens)
        self.diffButton.grid(row = 4, columnspan=4)
        self.diffButton.config(state="disabled") 

        # ROW 5
        self.data1Select = Entry(master,width=textWidth)
        self.data1Select.grid(row = 5, column = 0)

        self.data2Select = Entry(master,width=textWidth)
        self.data2Select.grid(row = 5, column = 1)

        # ROW 6   
        self.compareButton = Button(master, text="Compare Variables", command = self.compare)
        self.compareButton.grid(row = 6, columnspan = 2)
        self.compareButton.config(state="disabled")


    def getData(self):
        self.data1 = getXML(self.file1Selection.get(),self.versionSelection.get())
        self.data2 = getXML(self.file2Selection.get(),self.versionSelection.get())
        
        self.file1Screens.insert(END,"ALL")
        self.file2Screens.insert(END,"ALL")

        for screen in self.data1:
            self.file1Screens.insert(END,screen['title'])
        for screen in self.data2:
            self.file2Screens.insert(END,screen['title'])

        self.diffButton.config(state="normal")
        self.file1CsvButton.config(state="normal")
        self.file2CsvButton.config(state="normal")
        
    def checkMissingScreens(self):
        diffData = diffScreens(self.data1,self.data2)
        
        lastRow = len(diffData["data1missing"])
        if lastRow <= len(diffData["data2missing"]):
            lastRow = len(diffData["data2missing"])
        lastRow = lastRow+1

        if lastRow == 1:
            messagebox.showinfo("Result","They have no screen differences.") 
        else:
            top = Toplevel()
            top.columnconfigure(0,minsize=200)
            top.columnconfigure(1,minsize=200)

            titleLeft = Message(top, text=(self.file1Selection.get() + " is missing:"))
            titleLeft.config(aspect=400)
            titleLeft.grid(row=0,column=0)
            titleRight = Message(top, text=(self.file2Selection.get() + " is missing:"))
            titleRight.config(aspect=400)
            titleRight.grid(row=0,column=1)

            for index, screen in enumerate(diffData["data1missing"]):
                tmp = Message(top,text=screen)
                tmp.config(aspect=1500)
                tmp.grid(row=index+1,column=0)
            
            for index, screen in enumerate(diffData["data2missing"]):
                tmp = Message(top,text=screen)
                tmp.config(aspec=1500)
                tmp.grid(row=index+1,column=1)

            Button(top, text="Okay", command=top.destroy).grid(column=0, row=lastRow)
            Button(top, text="Save to CSV", command=lambda : writeCSVScreensDiff(diffData)).grid(column=1, row=lastRow)

    def saveCSV(self, f):
        if f == 1:
            n = self.file1Selection.get()
        elif f == 2:
            n = self.file2Selection.get()

        n = n.replace(".XML","")

        if f == 1:
            writeCSV(n,self.data1)
        elif f == 2:
            writeCSV(n,self.data2)

    def sendToCompare(self, f):
        if f == 1:
            self.data1Select.delete(0,END)
            self.data1Select.insert(0,self.file1Screens.get(ACTIVE))
            self.filled1 = True
        elif f == 2:
            self.data2Select.delete(0,END)
            self.data2Select.insert(0,self.file2Screens.get(ACTIVE))
            self.filled2 = True

        if self.filled1 and self.filled2:
            self.compareButton.config(state="normal")


    def compare(self):
        if self.data1Select.get() == "ALL" and self.data2Select.get() == "ALL":
            diffData = diffAll(self.data1,self.data2) 
            n = 0
            
            if not diffData:
                messagebox.showinfo("Result","There was no difference.")
                return

            for screen in diffData:
                n = n + len(screen['diffVars']) + len(screen['missingVars'])
            
            if n != 0:
                top = Toplevel()
                m = Message(top,text="There were "+ str(n) + " differences.")
                m.config(aspect=3000)
                m.grid(row=0,column=0,columnspan=2)
                Button(top,text="Okay",command=top.destroy).grid(row=1,column=1)
                Button(top,text="Save to CSV",command=lambda: writeCSVDiff(diffData)).grid(row=1,column=0)
            else:
                messagebox.showinfo("Result","There was no difference.")

        elif self.data1Select.get() == "ALL" or self.data2Select.get() == "ALL":
            messagebox.showinfo("Error","Both choices need to be ALL or neither choice needs to be ALL")

        else:
            for screen in self.data1:
                if screen['title'] == self.data1Select.get():
                    screen1 = screen
            for screen in self.data2:
                if screen['title'] == self.data2Select.get():
                    screen2 = screen
            diffData1 = diffScreenVars(screen1, screen2)
            diffData2 = diffScreenVars(screen2, screen1)

            if not diffData1 and not diffData2:
                messagebox.showinfo("Result","Both Screens are Equal")
            else:
                i = len(diffData1['missingVars']) + len(diffData1['diffVars']) + len(diffData2['missingVars']) + len(diffData2['diffVars'])
                top = Toplevel()
                m = Message(top,text="There were "+ str(i) + " differences.")
                m.config(aspect=3000)
                m.grid(row=0,column=0,columnspan=2)
                Button(top,text="Okay",command=top.destroy).grid(row=1,column=1)
                Button(top,text="Save to CSV",command=lambda: writeCSVDiff([diffData1,diffData2])).grid(row=1,column=0)

root = Tk()
root.title("xmldiffer (for screens) - thomas.barrett_ext@hoefliger.de")
root.geometry("600x400")
root.columnconfigure(0,weight=1)
root.columnconfigure(1,weight=1)
root.rowconfigure(0,weight=1)
root.rowconfigure(1,weight=1)
root.rowconfigure(2,weight=1)
root.rowconfigure(3,weight=1)
root.rowconfigure(4,weight=1)
root.rowconfigure(5,weight=1)
root.rowconfigure(6,weight=1)
app = XMLDiffer(master = root)
root.mainloop()
