#!/usr/bin/python3

from PyQt5.QtWidgets import QApplication, QFileDialog, QInputDialog, QMainWindow, QMessageBox, QSplitter
import sys

from lib.TreeModel import TreeModel
from lib.TreeView import TreeView
from lib.menubar import menubar
from lib.xmllib import compareXML
from lib.CONSTANTS import NONE

class diffML(QMainWindow):
    def __init__(self):
        super().__init__()

        self.frame = QSplitter()
        self.setCentralWidget(self.frame)

        menubar(self) 

        self.XMLViewOne = TreeView()
        self.frame.addWidget(self.XMLViewOne)

        self.XMLViewTwo = TreeView()
        self.frame.addWidget(self.XMLViewTwo)
        self.XMLViewTwo.hide()
        self.hasViewTwo = False

        self.XMLModelOne = False
        self.XMLModelTwo = False

        self.colorState = NONE

        self.show()
    
    def open(self):
        path = QFileDialog.getOpenFileName(self)
        if path[0]:
            model = TreeModel(path[0])
            if self.hasViewTwo:
                choice = QInputDialog.getItem(self, 'Open', 'Workspace:', ("1","2","Both"))
                if choice[0] == "1":
                    self.XMLModelOne = model
                    self.XMLViewOne.setModel(model)
                    self.XMLModelOne.setColor(self.colorState)

                elif choice[0] == "2":
                    self.XMLModelTwo = model
                    self.XMLViewTwo.setModel(model)
                    self.XMLModelTwo.setColor(self.colorState)

                else:
                    self.XMLModelOne = model
                    self.XMLViewOne.setModel(model)
                    self.XMLModelOne.setColor(self.colorState)
                    
                    model = TreeModel(path[0])
                    self.XMLModelTwo = model
                    self.XMLViewTwo.setModel(model)
                    self.XMLModelTwo.setColor(self.colorState)

            else:
                self.XMLModelOne = model
                self.XMLViewOne.setModel(model)
                self.XMLModelOne.setColor(self.colorState)

    def toggleViewTwo(self):
        if  self.hasViewTwo:
            self.hasViewTwo = False
            self.XMLViewTwo.hide()
        else:
            self.hasViewTwo = True
            self.XMLViewTwo.show()
    
    def setColor(self, color):
        self.colorState = color
        if self.XMLModelOne:
            self.XMLModelOne.setColor(color)
            self.XMLViewOne.setFocus()
        if self.XMLModelTwo:
            self.XMLModelTwo.setColor(color)
            self.XMLViewTwo.setNoneColor()
    
    def compare(self):
        choices = ("Tag","Text","Attribute")
        choice = QInputDialog.getItem(self, 'Compare Selected Elements', 'What to match with?', choices)

        selectedOne = self.XMLViewOne.selectedIndexes()

        if self.hasViewTwo:
            selectedTwo = self.XMLViewTwo.selectedIndexes()
            result = compareXML(choice[0],
                                self.XMLModelOne.getXMLTree(),
                                selectedOne,
                                self.XMLModelTwo.getXMLTree(),
                                selectedTwo)
            QMessageBox.question(self,'Result:','There were ' + str(len(result)) + ' differences.', QMessageBox.Save | QMessageBox.Ok)
            pprint(result)

    def save(self):
        if self.XMLModelOne:
            self.XMLModelOne.save()
        if self.XMLModelTwo:
            self.XMLModelTwo.save()
        
    def saveAs(self):
        if self.XMLModelTwo:
            choice = QInputDialog.getItem(self, 'Save As', 'Workspace:', ("1","2"))
            path = QFileDialog.getSaveFileName(self)
            if path[0] != '':
                if choice[0] == "1":
                        self.XMLModelOne.save(path[0])
                if choice[0] == "2":
                        self.XMLModelTwo.save(path[0])
        else:
            if self.XMLModelOne:
                path = QFileDialog.getSaveFileName(self)
                if path[0] != '':
                    self.XMLModelOne.save(path[0])

app = QApplication(sys.argv)

masterView = diffML()

sys.exit(app.exec_())
