#!/usr/bin/python3

from PyQt5.QtWidgets import QApplication, QTreeView, QGridLayout, QWidget, QFileDialog, QPushButton
from PyQt5.QtWidgets import QInputDialog, QMainWindow, QMessageBox
import sys

from pprint import pprint
from lib.treelib import TreeModel
from lib.xmllib import compareXML
from lib.barlib import menubar

class diffML(QMainWindow):
    def __init__(self):
        super().__init__()

        frame = QWidget()
        self.setCentralWidget(frame)
        self.grid = QGridLayout()
        frame.setLayout(self.grid)

        menubar(self) 

        self.XMLViewOne = QTreeView()
        self.grid.addWidget(self.XMLViewOne,0,0)

        self.addViewButton = QPushButton(">>")
        self.grid.addWidget(self.addViewButton,0,1)
        self.addViewButton.clicked.connect(self.addView)
        self.hasViewTwo = False

        self.show()
    
    def openXML(self):
        path = QFileDialog.getOpenFileName(self)
        if path[0]:
            model = TreeModel(path[0])
            if self.hasViewTwo:
                choices = ("1","2","Both")
                choice = QInputDialog.getItem(self, 'Open', 'Workspace:', choices)
                if choice[0] == "1":
                    self.XMLModelOne = model
                    self.XMLViewOne.setModel(model)
                elif choice[0] == "2":
                    self.XMLModelTwo = model
                    self.XMLViewTwo.setModel(model)
                else:
                    self.XMLModelOne = model
                    self.XMLViewOne.setModel(model)
                    model = TreeModel(path[0])
                    self.XMLModelTwo = model
                    self.XMLViewTwo.setModel(model)
            else:
                self.XMLModelOne = model
                self.XMLViewOne.setModel(model)

    def addView(self):
        self.hasViewTwo = True
        self.XMLViewTwo = QTreeView()
        self.grid.addWidget(self.XMLViewTwo,0,1)

    def colorize(self):
        self.XMLModelOne.colorize()
        if self.hasViewTwo:
            self.XMLModelTwo.colorize()

    def compare(self):
        choices = ("Tag","Text","Attribute")
        choice = QInputDialog.getItem(self, 'Compare Selected Elements', 'What to match with?', choices)

        selectedOne = self.XMLViewOne.selectedIndexes()

        if self.hasViewTwo:
            selectedTwo = self.XMLViewTwo.selectedIndexes()
            result = compareXML(choice[0],
                                self.XMLModelOne.getXMLTree(),
                                selectedOne,
                                self.XMLModelTwo.getXMLTree(),
                                selectedTwo)
            QMessageBox.question(self,'Result:','There were ' + str(len(result)) + ' differences.', QMessageBox.Save | QMessageBox.Ok)
            pprint(result)

    def saveXML(self):
        print("savin-")


app = QApplication(sys.argv)

masterView = diffML()

sys.exit(app.exec_())
