#!/usr/bin/python3

from PyQt5.QtCore import QFile, QIODevice
from PyQt5.QtWidgets import QApplication, QTreeView, QGridLayout, QWidget, QFileDialog, QPushButton
from PyQt5.QtWidgets import qApp, QInputDialog, QAction, QMainWindow
import sys

from lib.treelib import TreeModel
from lib.xmllib import compareXML

class xmlDiff(QMainWindow):
    def __init__(self):
        super().__init__()

        frame = QWidget()
        self.setCentralWidget(frame)
        self.grid = QGridLayout()
        frame.setLayout(self.grid)

        self.initMenuBar()

        self.XMLViewOne = QTreeView()
        self.grid.addWidget(self.XMLViewOne,0,0)

        self.addViewButton = QPushButton(">>")
        self.grid.addWidget(self.addViewButton,0,1)
        self.addViewButton.clicked.connect(self.addView)
        self.hasViewTwo = False

        self.show()
    
    def initMenuBar(self):
        menubar = self.menuBar()

        fileMenu = menubar.addMenu('&File')

        openXMLButton = QAction('&Open',self)
        openXMLButton.triggered.connect(self.openXML)
        fileMenu.addAction(openXMLButton)

        exitButton = QAction('&Exit',self)
        exitButton.triggered.connect(qApp.quit)
        fileMenu.addAction(exitButton)

        editMenu = menubar.addMenu('&Edit')

        viewMenu = menubar.addMenu('&View')

        colorizeButton = QAction('&Colorize',self)
        colorizeButton.triggered.connect(self.colorize)
        viewMenu.addAction(colorizeButton)
        
        compareButton = QAction('&Compare',self)
        compareButton.triggered.connect(self.compare)
        viewMenu.addAction(compareButton)
        
        helpMenu = menubar.addMenu('&Help')

    def openXML(self):
        path = QFileDialog.getOpenFileName(self)
        if path[0]:
            model = TreeModel(path[0])
            if self.hasViewTwo:
                choices = ("1","2")
                choice = QInputDialog.getItem(self, 'Open', 'Workspace:', choices)
                if choice[0] == "1":
                    self.XMLModelOne = model
                    self.XMLViewOne.setModel(model)
                else:
                    self.XMLModelTwo = model
                    self.XMLViewTwo.setModel(model)
            else:
                self.XMLModelOne = model
                self.XMLViewOne.setModel(model)

    def addView(self):
        self.hasViewTwo = True
        self.XMLViewTwo = QTreeView()
        self.grid.addWidget(self.XMLViewTwo,0,1)

    def colorize(self):
        self.XMLModelOne.colorize()
        if self.hasViewTwo:
            self.XMLModelTwo.colorize()

    def compare(self):
        selectedOne = self.XMLViewOne.selectedIndexes()
        if self.hasViewTwo:
            selectedTwo = self.XMLViewTwo.selectedIndexes()
        else:
            selectedTwo = None
        result = compareXML(selectedOne,selectedTwo)



app = QApplication(sys.argv)

masterView = xmlDiff()

sys.exit(app.exec_())
